### ISSUE TITLE
기능 제안: 훈련 코스

### ISSUE THREAD

**Issue by hotsixman** [exqt/donder-hiroba-plus#7]
# 훈련 코스(Training Course)

# 개요

본 기능은 여러 개의 곡과 그 곡에 대한 조건들로 이루어진, 훈련 코스를 생성하고 사용할 수 있도록 한다.

# 타입

## 훈련 코스

- 훈련 코스는 곡의 이름과 여러 개의 곡과 그 곡에 대한 조건들로 이루어져 있다.
- 조건은 개별 곡에 대해 적용되며, 훈련 코스에 대해 적용되지 않는다.
- 하나의 훈련 코스에서 곡은 중복될 수 없다.

```tsx
interface TrainingCourse{
	name: string;
	songs: TraningCourseSong[]
}
```

## 곡

- 곡은 곡 번호(songNo)와 조건들로 이루어져 있다.
- 각 곡에는 여러 개의 조건이 적용될 수 있다.

```tsx
interface TrainingCourseSong{
	songNo: number;
	conditions: TrainingCourseCondition[]
}
```

## 조건

- 조건은 다음 세가지 요소로 이루어져 있다.
    - 종류: 량, 가, 불가, 콤보, 연타, 두드린 횟수
    - 범위: 이상/이하
    - 기준치
- 조건의 종류는 중복될 수 없다.

```tsx
interface TrainingCourseCondition{
	type: 'good' | 'ok' | 'bad' | 'combo' | 'roll' | 'hit';
	range: 'more' | 'less'
	criterion: number
}
```

## 유저 데이터

- 유저 데이터는 코스와 각 곡에 대한 조건 충족 여부, 달성률로 이루어져 있다.
- 조건 충족 여부는 동더히로바에서는 최근 플레이 기록을 알 수 없기 때문에 베스트 스코어 기록을 기준으로 한다.
- $달성률 = \frac{조건\,충족한\,곡의\,개수}{전체\,곡의\,개수}$

```tsx
interface TrainingCourseUserData{
	course: TrainingCourse,
	achievements: Array<{
		songNo: number;
		met: boolean;
	}>,
	achievementRate: {
		numerator: number;
		denominator: number;
	}
}
```

# 작동

## 훈련 코스 표시

- 각 유저들이 추가한 훈련 코스들을 표시한다.
- 접힌 상태에서는 각 훈련 코스들의 이름과 달성률을 표시한다.
- 펼친 상태에서는 각 훈련 코스들의 곡과 각 곡의 조건 충족 여부, 수정 및 삭제, 내보내기 버튼을 표시한다.
- 내보내기 버튼을 누르면 해당 코스를 JSON화 하여 복사할 수 있도록 한다.

## 수정

- 각 곡의 순서의 수정, 조건 수정, 곡 삭제, 곡 추가가 가능하다.
- 수정 완료하면 유저 데이터에 자동 반영된다.

## 생성

- 훈련 코스를 생성하고 저장한다.
- 저장 완료하면 유저 데이터에 자동 반영된다.

## 새로 고침

- 베스트 스코어를 가져와 유저 데이터에 반영한다.
- 새로 고침을 하는 방법은 다음과 같다.
    - 새로 고침 버튼 클릭
    - 훈련 코스 생성/수정

**Comment by exqt** [comment]
- 조건은 range: 'more' | 'less' 는 필요없지 않을까요? 각 항목마다 more인지 less인지 하나만 정해질거 같은데 (예시: 양 개수 1000 이하 << 이런건 존재 의미가..)
- 위의 이유 때문에 type property말고 다 펼쳐 놓는것도 괜찮을거 같습니다. { good: 1024, ok: 50, roll: 100, bad: null, ... }
- 따로 플레이 상세 기록을 저장하는 기능이 추가되어야 할 것 같네요. 지금 있는 SongScoreDetail에 저번에 작성하신 PlaydataType을 합치면 좋을거 같네요. 이렇게 되면 TrainingCourseUserData는 저장할 필요는 없어 보이고 그냥 인터페이스 자체가 필요없어 보이네요

**Comment by hotsixman** [comment]
- SongScoreDetail에 하위 프로퍼티를 만들고 거기에 PlaydataType을 넣으면 좋을 것 같습니다.
```tsx
interface SongScoreDetail {
  crown: CrownType
  badge: BadgeType
  best?: {
    score: number
    good: number
    ok: number
    ng: number
    pound: number
    combo: number
    hit: number
  }
}
```
  이런식으로...
- 베스트 점수를 SongScoreDetail에 합쳐서 확장프로그램 저장소에 저장하면, 사용자가 추가한 코스만 따로 저장하면 될 것 같습니다.
- 단위도장 페이지에서 연주게임 베스트 기록을 보여주는 것은 그대로 접속할 때 마다 fetch를 통해 히로바에서 베스트 기록을 가져오되, 그 가져온 기록을 확장프로그램 저장소에 업데이트 하는 것이 좋을 것 같습니다.
